
DROP TABLE IF EXISTS user;
DROP TABLE IF EXISTS post;

CREATE TABLE user (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  firstname TEXT NOT NULL,
  lastname TEXT NOT NULL,
  email TEXT UNIQUE NOT NULL,
  password TEXT NOT NULL
);

CREATE TABLE class
 (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  classname TEXT NOT NULL,
  classtype TEXT NOT NULL,
  length TEXT NOT NULL,
  user_id INTEGER NOT NULL,

  -- created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

  FOREIGN KEY (user_id) REFERENCES user (id)
);

CREATE TABLE gpa (
id INTEGER PRIMARY KEY AUTOINCREMENT,
gpa REAL NOT NULL,
class_id INTEGER NOT NULL,

FOREIGN KEY (class_id) REFERENCES class (id)
)