
DROP TABLE IF EXISTS user;
DROP TABLE IF EXISTS post;

CREATE TABLE user (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  firstname TEXT NOT NULL,
  lastname TEXT NOT NULL,
  email TEXT UNIQUE NOT NULL,
  password TEXT NOT NULL
);

CREATE TABLE class
 (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  classname TEXT NOT NULL,
  classtype TEXT NOT NULL,
  length TEXT NOT NULL,
  user_id INTEGER NOT NULL,
  grade TEXT NOT NULL,
  -- gpa_id REAL NOT NULL, # idk about this

  -- created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

  FOREIGN KEY (user_id) REFERENCES user (id)
  -- FOREIGN KEY (gpa_id) REFERENCES gpa (id) --idk about this

);

CREATE TABLE gpa (
  id INTEGER PRIMARY KEY AUTOINCREMENT, --idk about this
  user_id INTEGER NOT NULL,
  gpa REAL NOT NULL,
-- id INTEGER PRIMARY KEY AUTOINCREMENT,

FOREIGN KEY (user_id) REFERENCES user (id)
)